name: Cargo Clippy

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: |
          cargo update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy
          cargo clippy --all-features
